require('Or1g3n.core.commands.autocommands')
require('Or1g3n.core.commands.markdown')
require('Or1g3n.core.commands.todos')
require('Or1g3n.core.commands.notebooks')
require('Or1g3n.core.commands.terminal')
